apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-application-set
spec:
  generators:
    - git:
        repoURL: https://github.com/dkstkdgur0612/hello-test.git
        revision: HEAD
        directories:
          - path: matrix-generator/*
  template:
    metadata:
      name: '{{path}}-myapp'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/dkstkdgur0612/hello-test.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc