apiVersion: batch/v1
kind: Job
metadata:
  generateName: success-job-
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: success-container
          image: busybox
          command: ["sh", "-c", "echo 'I always succeed!'"]
      restartPolicy: Never