apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: sync2-2
  labels:
    app: sync2-2
spec:
  selector:
    matchLabels:
      app: sync2-2
  replicas: 1
  template:
    metadata:
      name: sync2-2
      labels:
        app: sync2-2
    spec:
      initContainers:
        - name: init-sync2-2
          image: alpine
          command: ["sh", "-c", "sleep 60"]
      containers:
        - name: sync2-2
          image: alpine
          command: ["sh", "-c", "sleep 86400"]